---

- name: define hosts
  hosts: localhost
  gather_facts: no
  roles:
    - define_inventory

- name: stop emqx and clean logs
  hosts: emqx
  become: yes
  become_user: root
  roles:
    - stop_emqx
    - clean_logs

- name: clean loadgen bench logs
  hosts: loadgen
  become: yes
  become_user: root
  tasks:
    - name: remove stdout logs
      shell: "rm /tmp/*.?ub.* || true"
      ignore_errors: yes

- name: start cores
  hosts: cores
  become: yes
  become_user: root
  roles:
    - start_emqx

- name: start replicants
  hosts: replicants
  become: yes
  become_user: root
  roles:
    - start_emqx

...
