---

- hosts: emqx:loadgen
  tasks:
    # - name: copy releases
    #   file:
    #     src: "{{ item }}"
    #     dest: /tmp/
    #     mode: '0777'
    #   loop:
    #     - decurio-0.1.0.tar.gz
    #     - legionarius-0.1.0.tar.gz
    - name: create dirs
      file:
        path: "/tmp/{{ item }}"
        state: directory
      loop:
        - decurio
        - legionarius
    # - name: uncompress releases
    #   unarchive:
    #     src: "{{ item }}-0.1.0.tar.gz"
    #     dest: "/tmp/{{ item }}/"
    #   loop:
    #     - decurio
    #     - legionarius
    # - name: copy releases
    #   copy:
    #     src: "{{ item }}-0.1.0.tar.gz"
    #     dest: "/tmp/{{ item }}/"
    #   loop:
    #     - decurio
    #     - legionarius
    # - name: uncompress releases
    #   unarchive:
    #     src: "/tmp/{{ item }}-0.1.0.tar.gz"
    #     dest: "/tmp/{{ item }}/"
    #     remote_src: yes
    #   loop:
    #     - decurio
    #     - legionarius
    # - name: release?
    #   find:
    #     paths: "/tmp/"
    #     patterns:
    #       - "decurio.tar.gz"
    #       - "legionarius.tar.gz"
    #   register: releases
    # - debug:
    #     var: releases
    # - fail:
    #     msg: "{{ item not in (releases.files | map(attribute='path')) }}"
    #   loop:
    #     - decurio
    #     - legionarius
    - name: download release
      shell: |
        if [[ ! -f "/tmp/{{ item }}.tar.gz" || $force = yes ]]; then
          aws s3 cp s3://emqx-cdk-cluster/thales/100m-tests/packages/{{ item }}.tar.gz /tmp/{{ item }}.tar.gz
        fi
      vars:
        force: "{{ turma_download_force | default('no') }}"
      loop:
        - decurio
        - legionarius
    - name: uncompress releases
      unarchive:
        src: "/tmp/{{ item }}.tar.gz"
        dest: "/tmp/{{ item }}/"
        remote_src: yes
      loop:
        - decurio
        - legionarius
    - name: set config
      template:
        src: turma-runtime.exs
        dest: "/tmp/{{ item }}/releases/0.1.0/runtime.exs"
      loop:
        - decurio
        - legionarius
    - name: start legionarius
      become: yes
      become_user: root
      command: "/tmp/legionarius/bin/legionarius daemon_iex"

- hosts: loadgen[0]
  tasks:
    - name: start decurio
      become: yes
      become_user: root
      command: "/tmp/decurio/bin/decurio daemon_iex"

...
