---

- hosts: emqx:loadgen
  tasks:
    # - name: copy releases
    #   file:
    #     src: "{{ item }}"
    #     dest: /tmp/
    #     mode: '0777'
    #   loop:
    #     - decurio-0.1.0.tar.gz
    #     - legionarius-0.1.0.tar.gz
    - name: create dirs
      file:
        path: "/tmp/{{ item }}"
        state: directory
      loop:
        - decurio
        - legionarius
    # - name: uncompress releases
    #   unarchive:
    #     src: "{{ item }}-0.1.0.tar.gz"
    #     dest: "/tmp/{{ item }}/"
    #   loop:
    #     - decurio
    #     - legionarius
    # - name: copy releases
    #   copy:
    #     src: "{{ item }}-0.1.0.tar.gz"
    #     dest: "/tmp/{{ item }}/"
    #   loop:
    #     - decurio
    #     - legionarius
    # - name: uncompress releases
    #   unarchive:
    #     src: "/tmp/{{ item }}-0.1.0.tar.gz"
    #     dest: "/tmp/{{ item }}/"
    #     remote_src: yes
    #   loop:
    #     - decurio
    #     - legionarius
    - name: download release
      command: "aws s3 cp s3://emqx-cdk-cluster/thales/100m-tests/packages/{{ item }}.tar.gz /tmp/{{ item }}.tar.gz"
      loop:
        - decurio
        - legionarius
    - name: uncompress releases
      unarchive:
        src: "/tmp/{{ item }}.tar.gz"
        dest: "/tmp/{{ item }}/"
        remote_src: yes
      loop:
        - decurio
        - legionarius
    - name: set config
      template:
        src: turma-runtime.exs
        dest: "/tmp/{{ item }}/releases/0.1.0/runtime.exs"
    - name: start legionarius
      command: "/tmp/legionarius/bin/legionarius daemon_iex"

- hosts: loadgen[0]
  tasks:
    - name: start decurio
      command: "/tmp/decurio/bin/decurio daemon_iex"

...
