---

- hosts: emqx:loadgen
  tasks:
    - name: create dirs
      file:
        path: "/tmp/{{ item }}"
        state: directory
      loop:
        - decurio
        - legionarius
    - name: download release
      shell: |
        if [[ ! -f "/tmp/{{ item }}.tar.gz" || $force = yes ]]; then
          echo downloading...
          aws s3 cp s3://emqx-cdk-cluster/thales/100m-tests/packages/{{ item }}.tar.gz /tmp/{{ item }}.tar.gz
        else
          echo skipping...
        fi
      vars:
        force: "{{ turma_download_force | default('no') }}"
      loop:
        - decurio
        - legionarius
      register: download_res
    - debug:
        var: download_res
    - name: uncompress releases
      unarchive:
        src: "/tmp/{{ item }}.tar.gz"
        dest: "/tmp/{{ item }}/"
        remote_src: yes
      loop:
        - decurio
        - legionarius
    - name: set config
      template:
        src: turma-runtime.exs
        dest: "/tmp/{{ item }}/releases/0.1.0/runtime.exs"
      loop:
        - decurio
        - legionarius

- hosts: emqx:loadgen
  become: yes
  become_user: root
  roles:
    - restart_turma

...
