- name: stop systemd emqx
  systemd:
    name: emqx
    state: stopped
    daemon_reload: yes

- name: stop emqx
  block:
    - name: stop emqx
      shell: env EMQX_WAIT_FOR_STOP=20 emqx stop
      register: stop_result
      retries: 1
      delay: 3
      until: '"badrpc,timeout" not in stop_result.stderr'
      failed_when: '"badrpc,timeout" in stop_result.stderr'
  rescue:
    - name: REALLY stop emqx
      shell: "pkill -9 beam.smp"
