- name: stop systemd emqx
  systemd:
    name: emqx
    state: stopped
    daemon_reload: yes

- name: stop emqx
  block:
    - name: stop emqx
      shell: env EMQX_WAIT_FOR_STOP=20 emqx stop
      register: stop_result
      retries: 1
      delay: 3
      until: '"badrpc,timeout" not in stop_result.stderr'
      failed_when: '"badrpc,timeout" in stop_result.stderr'
    - name: check if emqx really stopped
      shell: "pgrep -a beam | grep '/usr/lib/emqx' | grep -v remsh"
      register: pgrep_beam_result
      failed_when: pgrep_beam_result.rc != 1
      changed_when: pgrep_beam_result.rc != 1
  rescue:
    - name: REALLY stop emqx
      shell: "pgrep -a beam | grep '/usr/lib/emqx' | grep -v remsh | awk '{ print $1; }' | xargs kill -9"
      ignore_errors: yes
